/*
 * Generated by gdbus-codegen 2.36.3. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "rfos.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface kmitl.ce.os.RFOS
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:RFOS
 * @title: RFOS
 * @short_description: Generated C code for the kmitl.ce.os.RFOS D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-kmitl-ce-os-RFOS.top_of_page">kmitl.ce.os.RFOS</link> D-Bus interface in C.
 */

/* ---- Introspection data for kmitl.ce.os.RFOS ---- */

static const _ExtendedGDBusArgInfo _rfos_method_info_put_IN_ARG_key =
{
  {
    -1,
    (gchar *) "key",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _rfos_method_info_put_IN_ARG_src =
{
  {
    -1,
    (gchar *) "src",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _rfos_method_info_put_IN_ARG_pointers[] =
{
  &_rfos_method_info_put_IN_ARG_key,
  &_rfos_method_info_put_IN_ARG_src,
  NULL
};

static const _ExtendedGDBusArgInfo _rfos_method_info_put_OUT_ARG_err =
{
  {
    -1,
    (gchar *) "err",
    (gchar *) "u",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _rfos_method_info_put_OUT_ARG_pointers[] =
{
  &_rfos_method_info_put_OUT_ARG_err,
  NULL
};

static const _ExtendedGDBusMethodInfo _rfos_method_info_put =
{
  {
    -1,
    (gchar *) "Put",
    (GDBusArgInfo **) &_rfos_method_info_put_IN_ARG_pointers,
    (GDBusArgInfo **) &_rfos_method_info_put_OUT_ARG_pointers,
    NULL
  },
  "handle-put",
  FALSE
};

static const _ExtendedGDBusArgInfo _rfos_method_info_get_IN_ARG_key =
{
  {
    -1,
    (gchar *) "key",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _rfos_method_info_get_IN_ARG_outpath =
{
  {
    -1,
    (gchar *) "outpath",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _rfos_method_info_get_IN_ARG_pointers[] =
{
  &_rfos_method_info_get_IN_ARG_key,
  &_rfos_method_info_get_IN_ARG_outpath,
  NULL
};

static const _ExtendedGDBusArgInfo _rfos_method_info_get_OUT_ARG_err =
{
  {
    -1,
    (gchar *) "err",
    (gchar *) "u",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _rfos_method_info_get_OUT_ARG_pointers[] =
{
  &_rfos_method_info_get_OUT_ARG_err,
  NULL
};

static const _ExtendedGDBusMethodInfo _rfos_method_info_get =
{
  {
    -1,
    (gchar *) "Get",
    (GDBusArgInfo **) &_rfos_method_info_get_IN_ARG_pointers,
    (GDBusArgInfo **) &_rfos_method_info_get_OUT_ARG_pointers,
    NULL
  },
  "handle-get",
  FALSE
};

static const _ExtendedGDBusArgInfo _rfos_method_info_remove_IN_ARG_key =
{
  {
    -1,
    (gchar *) "key",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _rfos_method_info_remove_IN_ARG_pointers[] =
{
  &_rfos_method_info_remove_IN_ARG_key,
  NULL
};

static const _ExtendedGDBusArgInfo _rfos_method_info_remove_OUT_ARG_err =
{
  {
    -1,
    (gchar *) "err",
    (gchar *) "u",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _rfos_method_info_remove_OUT_ARG_pointers[] =
{
  &_rfos_method_info_remove_OUT_ARG_err,
  NULL
};

static const _ExtendedGDBusMethodInfo _rfos_method_info_remove =
{
  {
    -1,
    (gchar *) "Remove",
    (GDBusArgInfo **) &_rfos_method_info_remove_IN_ARG_pointers,
    (GDBusArgInfo **) &_rfos_method_info_remove_OUT_ARG_pointers,
    NULL
  },
  "handle-remove",
  FALSE
};

static const _ExtendedGDBusArgInfo _rfos_method_info_search_IN_ARG_key =
{
  {
    -1,
    (gchar *) "key",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _rfos_method_info_search_IN_ARG_outpath =
{
  {
    -1,
    (gchar *) "outpath",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _rfos_method_info_search_IN_ARG_pointers[] =
{
  &_rfos_method_info_search_IN_ARG_key,
  &_rfos_method_info_search_IN_ARG_outpath,
  NULL
};

static const _ExtendedGDBusArgInfo _rfos_method_info_search_OUT_ARG_err =
{
  {
    -1,
    (gchar *) "err",
    (gchar *) "u",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _rfos_method_info_search_OUT_ARG_pointers[] =
{
  &_rfos_method_info_search_OUT_ARG_err,
  NULL
};

static const _ExtendedGDBusMethodInfo _rfos_method_info_search =
{
  {
    -1,
    (gchar *) "Search",
    (GDBusArgInfo **) &_rfos_method_info_search_IN_ARG_pointers,
    (GDBusArgInfo **) &_rfos_method_info_search_OUT_ARG_pointers,
    NULL
  },
  "handle-search",
  FALSE
};

static const _ExtendedGDBusArgInfo _rfos_method_info_stat_IN_ARG_key =
{
  {
    -1,
    (gchar *) "key",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _rfos_method_info_stat_IN_ARG_pointers[] =
{
  &_rfos_method_info_stat_IN_ARG_key,
  NULL
};

static const _ExtendedGDBusArgInfo _rfos_method_info_stat_OUT_ARG_size =
{
  {
    -1,
    (gchar *) "size",
    (gchar *) "u",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _rfos_method_info_stat_OUT_ARG_atime =
{
  {
    -1,
    (gchar *) "atime",
    (gchar *) "x",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _rfos_method_info_stat_OUT_ARG_err =
{
  {
    -1,
    (gchar *) "err",
    (gchar *) "u",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _rfos_method_info_stat_OUT_ARG_pointers[] =
{
  &_rfos_method_info_stat_OUT_ARG_size,
  &_rfos_method_info_stat_OUT_ARG_atime,
  &_rfos_method_info_stat_OUT_ARG_err,
  NULL
};

static const _ExtendedGDBusMethodInfo _rfos_method_info_stat =
{
  {
    -1,
    (gchar *) "Stat",
    (GDBusArgInfo **) &_rfos_method_info_stat_IN_ARG_pointers,
    (GDBusArgInfo **) &_rfos_method_info_stat_OUT_ARG_pointers,
    NULL
  },
  "handle-stat",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _rfos_method_info_pointers[] =
{
  &_rfos_method_info_put,
  &_rfos_method_info_get,
  &_rfos_method_info_remove,
  &_rfos_method_info_search,
  &_rfos_method_info_stat,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _rfos_interface_info =
{
  {
    -1,
    (gchar *) "kmitl.ce.os.RFOS",
    (GDBusMethodInfo **) &_rfos_method_info_pointers,
    NULL,
    NULL,
    NULL
  },
  "rfos",
};


/**
 * rfos_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-kmitl-ce-os-RFOS.top_of_page">kmitl.ce.os.RFOS</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
rfos_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_rfos_interface_info.parent_struct;
}

/**
 * rfos_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #RFOS interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
rfos_override_properties (GObjectClass *klass, guint property_id_begin)
{
  return property_id_begin - 1;
}



/**
 * RFOS:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-kmitl-ce-os-RFOS.top_of_page">kmitl.ce.os.RFOS</link>.
 */

/**
 * RFOSIface:
 * @parent_iface: The parent interface.
 * @handle_get: Handler for the #RFOS::handle-get signal.
 * @handle_put: Handler for the #RFOS::handle-put signal.
 * @handle_remove: Handler for the #RFOS::handle-remove signal.
 * @handle_search: Handler for the #RFOS::handle-search signal.
 * @handle_stat: Handler for the #RFOS::handle-stat signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-kmitl-ce-os-RFOS.top_of_page">kmitl.ce.os.RFOS</link>.
 */

static void
rfos_default_init (RFOSIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * RFOS::handle-put:
   * @object: A #RFOS.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_key: Argument passed by remote caller.
   * @arg_src: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-kmitl-ce-os-RFOS.Put">Put()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call rfos_complete_put() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-put",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (RFOSIface, handle_put),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    3,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING, G_TYPE_STRING);

  /**
   * RFOS::handle-get:
   * @object: A #RFOS.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_key: Argument passed by remote caller.
   * @arg_outpath: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-kmitl-ce-os-RFOS.Get">Get()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call rfos_complete_get() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-get",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (RFOSIface, handle_get),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    3,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING, G_TYPE_STRING);

  /**
   * RFOS::handle-remove:
   * @object: A #RFOS.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_key: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-kmitl-ce-os-RFOS.Remove">Remove()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call rfos_complete_remove() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-remove",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (RFOSIface, handle_remove),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  /**
   * RFOS::handle-search:
   * @object: A #RFOS.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_key: Argument passed by remote caller.
   * @arg_outpath: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-kmitl-ce-os-RFOS.Search">Search()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call rfos_complete_search() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-search",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (RFOSIface, handle_search),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    3,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING, G_TYPE_STRING);

  /**
   * RFOS::handle-stat:
   * @object: A #RFOS.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_key: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-kmitl-ce-os-RFOS.Stat">Stat()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call rfos_complete_stat() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-stat",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (RFOSIface, handle_stat),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

}

typedef RFOSIface RFOSInterface;
G_DEFINE_INTERFACE (RFOS, rfos, G_TYPE_OBJECT);

/**
 * rfos_call_put:
 * @proxy: A #RFOSProxy.
 * @arg_key: Argument to pass with the method invocation.
 * @arg_src: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-kmitl-ce-os-RFOS.Put">Put()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call rfos_call_put_finish() to get the result of the operation.
 *
 * See rfos_call_put_sync() for the synchronous, blocking version of this method.
 */
void
rfos_call_put (
    RFOS *proxy,
    const gchar *arg_key,
    const gchar *arg_src,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "Put",
    g_variant_new ("(ss)",
                   arg_key,
                   arg_src),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * rfos_call_put_finish:
 * @proxy: A #RFOSProxy.
 * @out_err: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to rfos_call_put().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with rfos_call_put().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
rfos_call_put_finish (
    RFOS *proxy,
    guint *out_err,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(u)",
                 out_err);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * rfos_call_put_sync:
 * @proxy: A #RFOSProxy.
 * @arg_key: Argument to pass with the method invocation.
 * @arg_src: Argument to pass with the method invocation.
 * @out_err: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-kmitl-ce-os-RFOS.Put">Put()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See rfos_call_put() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
rfos_call_put_sync (
    RFOS *proxy,
    const gchar *arg_key,
    const gchar *arg_src,
    guint *out_err,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "Put",
    g_variant_new ("(ss)",
                   arg_key,
                   arg_src),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(u)",
                 out_err);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * rfos_call_get:
 * @proxy: A #RFOSProxy.
 * @arg_key: Argument to pass with the method invocation.
 * @arg_outpath: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-kmitl-ce-os-RFOS.Get">Get()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call rfos_call_get_finish() to get the result of the operation.
 *
 * See rfos_call_get_sync() for the synchronous, blocking version of this method.
 */
void
rfos_call_get (
    RFOS *proxy,
    const gchar *arg_key,
    const gchar *arg_outpath,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "Get",
    g_variant_new ("(ss)",
                   arg_key,
                   arg_outpath),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * rfos_call_get_finish:
 * @proxy: A #RFOSProxy.
 * @out_err: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to rfos_call_get().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with rfos_call_get().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
rfos_call_get_finish (
    RFOS *proxy,
    guint *out_err,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(u)",
                 out_err);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * rfos_call_get_sync:
 * @proxy: A #RFOSProxy.
 * @arg_key: Argument to pass with the method invocation.
 * @arg_outpath: Argument to pass with the method invocation.
 * @out_err: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-kmitl-ce-os-RFOS.Get">Get()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See rfos_call_get() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
rfos_call_get_sync (
    RFOS *proxy,
    const gchar *arg_key,
    const gchar *arg_outpath,
    guint *out_err,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "Get",
    g_variant_new ("(ss)",
                   arg_key,
                   arg_outpath),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(u)",
                 out_err);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * rfos_call_remove:
 * @proxy: A #RFOSProxy.
 * @arg_key: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-kmitl-ce-os-RFOS.Remove">Remove()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call rfos_call_remove_finish() to get the result of the operation.
 *
 * See rfos_call_remove_sync() for the synchronous, blocking version of this method.
 */
void
rfos_call_remove (
    RFOS *proxy,
    const gchar *arg_key,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "Remove",
    g_variant_new ("(s)",
                   arg_key),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * rfos_call_remove_finish:
 * @proxy: A #RFOSProxy.
 * @out_err: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to rfos_call_remove().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with rfos_call_remove().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
rfos_call_remove_finish (
    RFOS *proxy,
    guint *out_err,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(u)",
                 out_err);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * rfos_call_remove_sync:
 * @proxy: A #RFOSProxy.
 * @arg_key: Argument to pass with the method invocation.
 * @out_err: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-kmitl-ce-os-RFOS.Remove">Remove()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See rfos_call_remove() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
rfos_call_remove_sync (
    RFOS *proxy,
    const gchar *arg_key,
    guint *out_err,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "Remove",
    g_variant_new ("(s)",
                   arg_key),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(u)",
                 out_err);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * rfos_call_search:
 * @proxy: A #RFOSProxy.
 * @arg_key: Argument to pass with the method invocation.
 * @arg_outpath: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-kmitl-ce-os-RFOS.Search">Search()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call rfos_call_search_finish() to get the result of the operation.
 *
 * See rfos_call_search_sync() for the synchronous, blocking version of this method.
 */
void
rfos_call_search (
    RFOS *proxy,
    const gchar *arg_key,
    const gchar *arg_outpath,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "Search",
    g_variant_new ("(ss)",
                   arg_key,
                   arg_outpath),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * rfos_call_search_finish:
 * @proxy: A #RFOSProxy.
 * @out_err: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to rfos_call_search().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with rfos_call_search().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
rfos_call_search_finish (
    RFOS *proxy,
    guint *out_err,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(u)",
                 out_err);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * rfos_call_search_sync:
 * @proxy: A #RFOSProxy.
 * @arg_key: Argument to pass with the method invocation.
 * @arg_outpath: Argument to pass with the method invocation.
 * @out_err: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-kmitl-ce-os-RFOS.Search">Search()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See rfos_call_search() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
rfos_call_search_sync (
    RFOS *proxy,
    const gchar *arg_key,
    const gchar *arg_outpath,
    guint *out_err,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "Search",
    g_variant_new ("(ss)",
                   arg_key,
                   arg_outpath),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(u)",
                 out_err);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * rfos_call_stat:
 * @proxy: A #RFOSProxy.
 * @arg_key: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-kmitl-ce-os-RFOS.Stat">Stat()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call rfos_call_stat_finish() to get the result of the operation.
 *
 * See rfos_call_stat_sync() for the synchronous, blocking version of this method.
 */
void
rfos_call_stat (
    RFOS *proxy,
    const gchar *arg_key,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "Stat",
    g_variant_new ("(s)",
                   arg_key),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * rfos_call_stat_finish:
 * @proxy: A #RFOSProxy.
 * @out_size: (out): Return location for return parameter or %NULL to ignore.
 * @out_atime: (out): Return location for return parameter or %NULL to ignore.
 * @out_err: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to rfos_call_stat().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with rfos_call_stat().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
rfos_call_stat_finish (
    RFOS *proxy,
    guint *out_size,
    gint64 *out_atime,
    guint *out_err,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(uxu)",
                 out_size,
                 out_atime,
                 out_err);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * rfos_call_stat_sync:
 * @proxy: A #RFOSProxy.
 * @arg_key: Argument to pass with the method invocation.
 * @out_size: (out): Return location for return parameter or %NULL to ignore.
 * @out_atime: (out): Return location for return parameter or %NULL to ignore.
 * @out_err: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-kmitl-ce-os-RFOS.Stat">Stat()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See rfos_call_stat() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
rfos_call_stat_sync (
    RFOS *proxy,
    const gchar *arg_key,
    guint *out_size,
    gint64 *out_atime,
    guint *out_err,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "Stat",
    g_variant_new ("(s)",
                   arg_key),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(uxu)",
                 out_size,
                 out_atime,
                 out_err);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * rfos_complete_put:
 * @object: A #RFOS.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @err: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-kmitl-ce-os-RFOS.Put">Put()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
rfos_complete_put (
    RFOS *object,
    GDBusMethodInvocation *invocation,
    guint err)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(u)",
                   err));
}

/**
 * rfos_complete_get:
 * @object: A #RFOS.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @err: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-kmitl-ce-os-RFOS.Get">Get()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
rfos_complete_get (
    RFOS *object,
    GDBusMethodInvocation *invocation,
    guint err)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(u)",
                   err));
}

/**
 * rfos_complete_remove:
 * @object: A #RFOS.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @err: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-kmitl-ce-os-RFOS.Remove">Remove()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
rfos_complete_remove (
    RFOS *object,
    GDBusMethodInvocation *invocation,
    guint err)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(u)",
                   err));
}

/**
 * rfos_complete_search:
 * @object: A #RFOS.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @err: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-kmitl-ce-os-RFOS.Search">Search()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
rfos_complete_search (
    RFOS *object,
    GDBusMethodInvocation *invocation,
    guint err)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(u)",
                   err));
}

/**
 * rfos_complete_stat:
 * @object: A #RFOS.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @size: Parameter to return.
 * @atime: Parameter to return.
 * @err: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-kmitl-ce-os-RFOS.Stat">Stat()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
rfos_complete_stat (
    RFOS *object,
    GDBusMethodInvocation *invocation,
    guint size,
    gint64 atime,
    guint err)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(uxu)",
                   size,
                   atime,
                   err));
}

/* ------------------------------------------------------------------------ */

/**
 * RFOSProxy:
 *
 * The #RFOSProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * RFOSProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #RFOSProxy.
 */

struct _RFOSProxyPrivate
{
  GData *qdata;
};

static void rfos_proxy_iface_init (RFOSIface *iface);

G_DEFINE_TYPE_WITH_CODE (RFOSProxy, rfos_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (TYPE_RFOS, rfos_proxy_iface_init));

static void
rfos_proxy_finalize (GObject *object)
{
  RFOSProxy *proxy = RFOS_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (rfos_proxy_parent_class)->finalize (object);
}

static void
rfos_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
}

static void
rfos_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
}

static void
rfos_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_rfos_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], TYPE_RFOS);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_RFOS);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
rfos_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  RFOSProxy *proxy = RFOS_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_rfos_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_rfos_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
rfos_proxy_init (RFOSProxy *proxy)
{
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, TYPE_RFOS_PROXY, RFOSProxyPrivate);
  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), rfos_interface_info ());
}

static void
rfos_proxy_class_init (RFOSProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  g_type_class_add_private (klass, sizeof (RFOSProxyPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = rfos_proxy_finalize;
  gobject_class->get_property = rfos_proxy_get_property;
  gobject_class->set_property = rfos_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = rfos_proxy_g_signal;
  proxy_class->g_properties_changed = rfos_proxy_g_properties_changed;

}

static void
rfos_proxy_iface_init (RFOSIface *iface)
{
}

/**
 * rfos_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-kmitl-ce-os-RFOS.top_of_page">kmitl.ce.os.RFOS</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call rfos_proxy_new_finish() to get the result of the operation.
 *
 * See rfos_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
rfos_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_RFOS_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "kmitl.ce.os.RFOS", NULL);
}

/**
 * rfos_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to rfos_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with rfos_proxy_new().
 *
 * Returns: (transfer full) (type RFOSProxy): The constructed proxy object or %NULL if @error is set.
 */
RFOS *
rfos_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return RFOS (ret);
  else
    return NULL;
}

/**
 * rfos_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-kmitl-ce-os-RFOS.top_of_page">kmitl.ce.os.RFOS</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See rfos_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type RFOSProxy): The constructed proxy object or %NULL if @error is set.
 */
RFOS *
rfos_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_RFOS_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "kmitl.ce.os.RFOS", NULL);
  if (ret != NULL)
    return RFOS (ret);
  else
    return NULL;
}


/**
 * rfos_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like rfos_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call rfos_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See rfos_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
rfos_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_RFOS_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "kmitl.ce.os.RFOS", NULL);
}

/**
 * rfos_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to rfos_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with rfos_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type RFOSProxy): The constructed proxy object or %NULL if @error is set.
 */
RFOS *
rfos_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return RFOS (ret);
  else
    return NULL;
}

/**
 * rfos_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like rfos_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See rfos_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type RFOSProxy): The constructed proxy object or %NULL if @error is set.
 */
RFOS *
rfos_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_RFOS_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "kmitl.ce.os.RFOS", NULL);
  if (ret != NULL)
    return RFOS (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * RFOSSkeleton:
 *
 * The #RFOSSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * RFOSSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #RFOSSkeleton.
 */

struct _RFOSSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_rfos_skeleton_handle_method_call (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  RFOSSkeleton *skeleton = RFOS_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], TYPE_RFOS);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_RFOS);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_rfos_skeleton_handle_get_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  RFOSSkeleton *skeleton = RFOS_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_rfos_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_rfos_skeleton_handle_set_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  RFOSSkeleton *skeleton = RFOS_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_rfos_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _rfos_skeleton_vtable =
{
  _rfos_skeleton_handle_method_call,
  _rfos_skeleton_handle_get_property,
  _rfos_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
rfos_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton)
{
  return rfos_interface_info ();
}

static GDBusInterfaceVTable *
rfos_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton)
{
  return (GDBusInterfaceVTable *) &_rfos_skeleton_vtable;
}

static GVariant *
rfos_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  RFOSSkeleton *skeleton = RFOS_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_rfos_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _rfos_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _rfos_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _rfos_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "kmitl.ce.os.RFOS", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
rfos_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
}

static void rfos_skeleton_iface_init (RFOSIface *iface);
G_DEFINE_TYPE_WITH_CODE (RFOSSkeleton, rfos_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (TYPE_RFOS, rfos_skeleton_iface_init));

static void
rfos_skeleton_finalize (GObject *object)
{
  RFOSSkeleton *skeleton = RFOS_SKELETON (object);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (rfos_skeleton_parent_class)->finalize (object);
}

static void
rfos_skeleton_init (RFOSSkeleton *skeleton)
{
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, TYPE_RFOS_SKELETON, RFOSSkeletonPrivate);
  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
}

static void
rfos_skeleton_class_init (RFOSSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  g_type_class_add_private (klass, sizeof (RFOSSkeletonPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = rfos_skeleton_finalize;

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = rfos_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = rfos_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = rfos_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = rfos_skeleton_dbus_interface_get_vtable;
}

static void
rfos_skeleton_iface_init (RFOSIface *iface)
{
}

/**
 * rfos_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-kmitl-ce-os-RFOS.top_of_page">kmitl.ce.os.RFOS</link>.
 *
 * Returns: (transfer full) (type RFOSSkeleton): The skeleton object.
 */
RFOS *
rfos_skeleton_new (void)
{
  return RFOS (g_object_new (TYPE_RFOS_SKELETON, NULL));
}

